### ISSUE TITLE
Script doesn't check for existing database record with Non-owned vehicles

### ISSUE THREAD

**Issue by XenSide** [Trsak/esx_inventoryhud_trunk#15]
As I've alredy described in issue #12 , the script registers a record with plate as primary key every time someone opens a vehicle that has the flag "owned" = 0, while this is fine the problem comes from the fact that you don't check whether an existing record is present or not. 

What basically happens is that if you try to open the same trunk a couple of times you'll get an error because you're trying to create a record with an already used PrimaryKey.

This is quite a big issue.

**Comment by TheStonedRaider** [comment]
Yes ive been seeing a duplicate error pop up many times. when there is 10+ people on its usualy filling the console. not really helpful for monitoring the server.

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
