### ISSUE TITLE
Suggestion: Inventory Grid

### ISSUE THREAD

**Issue by XenSide** [Trsak/esx_inventoryhud_trunk#16]
Just a small suggestion: 
Instead of having the inventory planned out like it alredy is, you could make a grid of configurable lenght in which you can move items around so you can order your items as you wish.

**Comment by DJJeffP** [comment]
Agree, that would be nice!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by XenSide** [comment]
This should me more a suggestion for the original script rather than the addon, I'm closing the Issue and reopening it in the repo for the script.
