### ISSUE TITLE
Individual vehicles weights

### ISSUE THREAD

**Issue by zek0** [Trsak/esx_inventoryhud_trunk#17]
First off big Thank Trsak for great script! Maybe in future will be possible make individual vehicles weights of trunk instead of classes? Like this: 

Config.VehicleLimit = {
adder = 1000,
biff = 30000,
taxi = 200
}

That will be a great option.
Thank you again.

**Comment by JogiTE** [comment]
oh yes that would be very nice

**Comment by Pengich** [comment]
+1 please make this a thing

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
