### ISSUE TITLE
for some reasons when u put in esx_advancedgarage

### ISSUE THREAD

**Issue by pashkalt** [Trsak/esx_inventoryhud_trunk#18]
Hey, for some reasons when u put a car with items in inventory it dissapear for users, can someone know this issue and how to fix it?

**Comment by NextGenRP** [comment]
in the server lua, find the mysql line DELETE FROM and comment it out,

**Comment by bsdesire** [comment]
> in the server lua, find the mysql line DELETE FROM and comment it out,

is it this line?

`AddEventHandler(
  "onMySQLReady",
  function()
    MySQL.Async.execute("DELETE FROM `trunk_inventory` WHERE `owned` = 0", {})
  end
)`

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
