### ISSUE TITLE
Y problem

### ISSUE THREAD

**Issue by mamadlooloo** [Trsak/esx_inventoryhud_trunk#20]
hello
please help me
when i push Y trunk open but menu not shown to me and i get this error

-----------------------------------------
stack traceback:
        @esx_inventoryhud_trunk/server/trunk.lua:71: in function 'getOwnedVehicu
le'
        @esx_inventoryhud_trunk/server/trunk.lua:83: in function 'MakeDataStore'

        @esx_inventoryhud_trunk/server/trunk.lua:98: in function 'GetSharedDataS
tore'
        @esx_inventoryhud_trunk/server/trunk.lua:106: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scriptin
g/lua/scheduler.lua:218>
Error resuming coroutine: @esx_inventoryhud_trunk/server/trunk.lua:71: attempt t
o index a nil value (local 'vehicle')

**Comment by mamadlooloo** [comment]
do i remove some lines in "esx_extended" ?

**Comment by mamadlooloo** [comment]
do i change my server.cfg ?
-------------------------------

start RealisticVehicleFailure
start LegacyFuel
start esx_fwd_ui

# -------------------------------
start pNotify
start esx_inventoryhud
start esx_inventoryhud_trunk

**Comment by moler14** [comment]
you do not need to change anything in es_extended, make sure the vehicle is registered to you and stored in your database

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
