### ISSUE TITLE
This trunk is closed?

### ISSUE THREAD

**Issue by berdancanyet** [Trsak/esx_inventoryhud_trunk#22]
When i try to open my personal vehicle's trunk it say "this trunk is closed" Even though i opened the trunk with vehicle control menu, it did not work.

**Comment by moler14** [comment]
Do you own the vehicle, spawned vehicles will not work, you must be the registered vehicle owner.

**Comment by berdancanyet** [comment]
What about the job spawned cars & trucks?

**Comment by berdancanyet** [comment]
Alright, i did some editings and solved the problem.

**Comment by RandomZFx** [comment]
How did you fix @berdancanyet
