### ISSUE TITLE
[Sugestion] - Backpack

### ISSUE THREAD

**Issue by Leonardoth** [Trsak/esx_inventoryhud_trunk#23]
When I drop a item, i know that there's a bag that SOMETIMES appear depending on your distance to the item, but it does not render correctly and if you move it disappears.
I was wondering if you could place just a bag (i'm thinking of the way that nopixel has) that we could see from anywhere and that we could OPEN with a hotkey, so when our inventory is full, we wouldn't be spammed with text.

tl:dr
- Backpacks on the floor (act as a "inventory" with a radius, every item dropped really close to it, will get added to that backpack and the player has to open with a interaction key)

**Comment by moler14** [comment]
what your asking would be much better in its own package, as every new bag spawned would have to have its own stored data to make sure things wernt duplicated ect ( exactly why the trunk addon is seperate ) and you have to realise....not everybody knows what no pixel is...if you want things to replicate no pixel... then join no pixel, or develop it and release it to esx ;)

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
