### ISSUE TITLE
Item loss

### ISSUE THREAD

**Issue by thegambid** [Trsak/esx_inventoryhud_trunk#29]
Some of my players are complaining when they put items in garage (esx_jb_eden_garage2) and log out and then log in back they says trunk is empty. What to do?

**Comment by Hamza8700** [comment]
We are experiencing same issue.
Players put their items into the trunk, park the vehicle. When they re-log, everything is gone from that particular trunk.

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
