### ISSUE TITLE
Black Money

### ISSUE THREAD

**Issue by bellane** [Trsak/esx_inventoryhud_trunk#3]
Any way to remove this 0 black money from trunk? Was in there by default.

https://gyazo.com/acf8779b5b3fc6bdcd84a0470ead121a

**Comment by RoqueDEV** [comment]
Yes that is possible, go to esx_inventoryhud and then client and then main.lua and then line 441 https://github.com/Trsak/esx_inventoryhud/blob/f75d42a620d2325eedeba97d9a3ade08486b626d/client/main.lua#L441 and change `if blackMoney >= 0 then` to `if blackMoney > 0 then`

**Comment by Trsak** [comment]
Fixed.
