### ISSUE TITLE
Made a Bug fix for the PlayerData = nil when changing jobs!

### ISSUE THREAD

**Issue by DJJeffP** [Trsak/esx_inventoryhud_trunk#32]
I was having issues with the script where I changed job that the following error was coming true:

> Error resuming coroutine: @esx_inventoryhud_trunk/client/esx_trunk-cl.lua 51: attempt to index a nil value (upvalue 'PlayerData' )

This means that the PlayerData was having a nil instead of a table value,
How I fixed it?
I did the following:

In client/esx_trunk-cl.lua:
Line 14 to 26
> 
> Citizen.CreateThread(
>   function()
>     while ESX == nil do
>       TriggerEvent(
>         "esx:getSharedObject",
>         function(obj)
>           ESX = obj
>         end
>       )
>       Citizen.Wait(0)
>     end
>   end)

Replaced it to:

> Citizen.CreateThread(function()
>   while ESX == nil do
>     TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
>     Citizen.Wait(0)
>   end
>   
>   while ESX.GetPlayerData().job == nil do
>     Citizen.Wait(10)
>   end
> 
>   PlayerData = ESX.GetPlayerData()
> end)

line 47 to 53:

> RegisterNetEvent("esx:setJob")
> AddEventHandler(
>   "esx:setJob",
>   function(job)
>     PlayerData.job = job
>   end)

Replaced it to:

> RegisterNetEvent("esx:setJob")
> AddEventHandler("esx:setJob", function(job)
>   while PlayerData == nil do
>     Citizen.Wait(1000)
>   end
> 
>   print("Job: ", job)
>   print("PlayerData: ", PlayerData)
>   
>   PlayerData.job = job
>   onDuty = false
>   myPlate = {} -- loosing vehicle caution in case player changes job.
>   spawner = 0
> end)

Hope this will help you guys also solving this issue.

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
