### ISSUE TITLE
Unknown Trunk Issue

### ISSUE THREAD

**Issue by techniciantucker** [Trsak/esx_inventoryhud_trunk#34]
https://gyazo.com/e1e6cafffe4fa7c1d374b475653debe7

**Comment by techniciantucker** [comment]
The trunks wont open and just throws the error in the screenshot above.. It was working fine until I updated my artifacts.

**Comment by techniciantucker** [comment]
Ignore this... It was something in my db.. My owned vehicles had a blank row.. causing that error..

**Comment by SilvNobelen** [comment]
> Ignore this... It was something in my db.. My owned vehicles had a blank row.. causing that error..

I have the same issue, wich row was wrong by you?
