### ISSUE TITLE
Cant lock trunk and sometime error in console

### ISSUE THREAD

**Issue by kFxDaKing** [Trsak/esx_inventoryhud_trunk#35]
Error resuming coroutine: @esx_inventoryhud_trunk/server/trunk.lua:57: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'string.find'
	@esx_inventoryhud_trunk/server/trunk.lua:57: in function 'getOwnedVehicule'
	@esx_inventoryhud_trunk/server/trunk.lua:83: in function 'MakeDataStore'
	@esx_inventoryhud_trunk/server/trunk.lua:98: in function 'GetSharedDataStore'
	@esx_inventoryhud_trunk/server/trunk.lua:106: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:169: in function <citizen:/scripting/lua/scheduler.lua:168>

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
