### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by kFxDaKing** [Trsak/esx_inventoryhud_trunk#36]
SCRIPT ERROR: @esx_inventoryhud_trunk/server/trunk.lua:57: bad argument #1 to 'find' (string expected, got nil)
> getOwnedVehicule (@esx_inventoryhud_trunk/server/trunk.lua:57)
> MakeDataStore (@esx_inventoryhud_trunk/server/trunk.lua:83)
> GetSharedDataStore (@esx_inventoryhud_trunk/server/trunk.lua:98)
> handler (@esx_inventoryhud_trunk/server/trunk.lua:106)
> ref (@esx_inventoryhud_trunk/server/esx_trunk-sv.lua:96)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)

**Comment by redskatex** [comment]
you resolve ? i have same problem

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
