### ISSUE TITLE
When I try to open the trunk it tells me that the vehicle is locked

### ISSUE THREAD

**Issue by maximainero** [Trsak/esx_inventoryhud_trunk#38]
I already tried commenting on that part of the code (line 44,76,77 and 78 in client lua) but it still doesn't show me the inventory. some help? Thanks!

**Comment by davem1988** [comment]
I have the same problem! I have esx_inventoryhud_glovebox and it work perfectly! I dont understand i parked the car in my garage then qui restart the server and came back end it still locked!
