### ISSUE TITLE
Sometimes SCRIPT ERROR: @esx_inventoryhud_trunk/server/trunk.lua:72: table index is nil

### ISSUE THREAD

**Issue by badchulo** [Trsak/esx_inventoryhud_trunk#39]
IDK why sometimes console says:
SCRIPT ERROR: @esx_inventoryhud_trunk/server/trunk.lua:72: table index is nil
> ref (@esx_inventoryhud_trunk/server/trunk.lua:72)
>  (@mysql-async/mysql-async.js:15543)

and user can't open trunk

**Comment by DJJeffP** [comment]
Please Check you database if the vehicle is correct in the database. I think you missing some fields there with the necessary info for the inventoryhud. Or the database link could not be established. Because then it will return a nil value.

**Comment by badchulo** [comment]
> 
> 
> Or the database link could not be established. Because then it will return a nil value.

I think probably was that cause now looks like it's working fine

Ty i will close the issue
