### ISSUE TITLE
when i tried to get item from trunk, i'm not getting the item

### ISSUE THREAD

**Issue by wilsonfred** [Trsak/esx_inventoryhud_trunk#40]
please help, cannot get the item from the trunk

**Comment by argykaraz** [comment]
It uses the "limit" value to get the items. Go to your Database and check the items. Is the a column called "Weight:? If yes then, just open esx_inventoryhud_trunk\server\esx_trunk-sv.lua
Go to line: 110 and replace this:
if targetItem.limit == -1 or ((targetItem.count + count) <= targetItem.limit) then
with this:
if targetItem.weight == -1 or ((targetItem.count + count) <= targetItem.weight) then

**Comment by rustyneedles** [comment]
I get a no vehicle nearby even when im standing up against the vehicle

**Comment by Uriahartega** [comment]
Did you find the fix for this i tried what was suggested but i still cant drag items back out of trunk

**Comment by ikTray** [comment]
+ Bump

**Comment by Trsak** [comment]
If it does not work for you, then you have most probably newer esx version and need to update your code as mentioned by @argykaraz.

**Comment by ikTray** [comment]
> Did you find the fix for this i tried what was suggested but i still cant drag items back out of trunk

I got it to work.
