### ISSUE TITLE
SCRIPTS ERROR @esx_inventoryhud_trunk/server/trunk.lua:72: table index is nil.

### ISSUE THREAD

**Issue by diepmiho** [Trsak/esx_inventoryhud_trunk#43]
My players are sometimes cant open their trunk  and that error happens once in a while what should i do? Please help im not that good at Lua yet so i dont know much :(

**Comment by fsjNk** [comment]
> My players are sometimes cant open their trunk and that error happens once in a while what should i do? Please help im not that good at Lua yet so i dont know much :(

Did you manage to fix this ? I have the same issue

**Comment by Trsak** [comment]
Looks like getting plate is not working for you.
