### ISSUE TITLE
When put in money, turn to black money.

### ISSUE THREAD

**Issue by EndlessGOOOD** [Trsak/esx_inventoryhud_trunk#44]
Hello!

Main issue is, if i modify Config.IncludeCash to true, i have multiple MONEY in inventory panel.
But, if make it to false, i have only once but i can't drop and give it to other players ..

Every single time when i put in normal money in to trunk ( from account money, not simple money ) its turn into black money .. how can i figure out that issue?

**Comment by AntonyMax** [comment]
Did you fix the problem ?

**Comment by PenguinAugis** [comment]
Hello, any news?

**Comment by Trsak** [comment]
If it does not work for you, then you have most probably newer esx version and need to update your code as @argykaraz mentioned.
