### ISSUE TITLE
Trunk opens only once & Drag and Drop problem!

### ISSUE THREAD

**Issue by SyntaxYT2020** [Trsak/esx_inventoryhud_trunk#46]
If I go to the trunk and open it, it works perfectly. As soon as I close it and try again, it doesn't open. Only after I restart the server or my client can I open it again. Help

The first time I try to open items, it doesn't work. No errors etc. are dropped! the drag and drop does not work

**Comment by jessieBoyer** [comment]
Having the trunk only open once as well. Drag and drop was fixed by adding the trunk.lua from his newer inventory hud

**Comment by jessieBoyer** [comment]
Looks like this is fixed if you use the newest version of the inventoryhud. hope this helps.
