### ISSUE TITLE
Players can see trunk at same time and dupe

### ISSUE THREAD

**Issue by hur1can** [Trsak/esx_inventoryhud_trunk#7]
Title

**Comment by Zerefdev** [comment]
Well, every trunk inventory has that problem.
Check is this option
`Config.CheckOwnership = false -- If true, Only owner of vehicle can store items in trunk.`
make this to true and only vehicle owners can access the trunk

**Comment by 88Flak** [comment]
Not really, a previous trunk script I used disabled the trunks by vehicle plate to prevent duping

**Comment by Trsak** [comment]
Closing since I have released new reworked version.
